[package]
name = "embassy-nxp"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.0"
critical-section = "1.1.2"
embassy-hal-internal = { version = "0.2.0", path = "../embassy-hal-internal", features = ["cortex-m", "prio-bits-2"] }
embassy-sync = { version = "0.7.0", path = "../embassy-sync" }
defmt = { version = "1", optional = true }

## Chip dependencies
lpc55-pac = { version = "0.5.0", optional = true }

[features]
default = ["rt"]
# Enable PACs as optional dependencies, since some chip families will use different pac crates.
rt = ["lpc55-pac?/rt"]

## Enable [defmt support](https://docs.rs/defmt) and enables `defmt` debug-log messages and formatting in embassy drivers.
defmt = ["dep:defmt", "embassy-hal-internal/defmt", "embassy-sync/defmt"]

#! ### Chip selection features
lpc55 = ["lpc55-pac"]
